from panda3d.core import Vec4
from core.config import GRAVITY

VIDEO_FRAME_RATE = 60

INIT_CAM_DISTANCE = 30
MIN_CAM_DISTANCE = 1e-3
MAX_CAM_DISTANCE = 1e3
ZOOM_FACTOR = .25
MOUSE_SPEED = 100
CAM_LENS_NEAR_FACTOR = .1
VIEW_CHANGE_SPEED = .1

MODELS_WIREFRAME_COLOR = .3
MODELS_DIRECTIONAL_COLOR = .5
MODELS_AMBIENT_LIGHT_COLOR = .5
VISUAL_AMBIENT_LIGHT_COLOR = .8
BACKGROUND_COLOR = (.9, .9, .9)
DEBUG_BACKGROUND_COLOR = (.1, .1, .1)
GRID_COLOR = .35
BUTTON_COLOR_1 = Vec4(65, 105, 225, 255)/255

PHYSICS_FRAME_RATE = 240

SCENARIO_INVALID_COLOR = (1, 0, 0, 1)
SCENARIO_SUCCESS_COLOR = (0, 1, 0, 1)
SCENARIO_TIMEOUT_COLOR = (1, .5, 0, 1)
